- name: Gather Java package facts
  hosts: all
  gather_facts: true
  vars:
    java_packages:
      - java
      - jdk
      - jre
  tasks:
    - name: Get installed Java packages
      command: rpm -qa | grep "{{ java_packages | join(' ') }}"
      register: java_packages_output

    - name: Filter for Red Hat 7 and above
      set_fact:
        redhat: "{{ ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] | int >= 7 }}"

    - name: Filter for Java packages
      set_fact:
        java_installed: "{{ java_packages_output.stdout_lines }}"

    - name: Write Java package facts to CSV file
      lineinfile:
        path: /tmp/java_packages.csv
        line: "{{ ansible_facts['hostname'] }},{{ java_installed | join(',') }}"
      when: redhat and java_installed
