- name: Gather Java package facts
  hosts: all
  gather_facts: true

  vars:
    java_packages:
      - java
      - jdk
      - jre

  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
      register: package_facts

    - name: Filter for Red Hat 7 and above
      set_fact:
        redhat: "{{ ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] | int >= 7 }}"

    - name: Filter for Java packages
      set_fact:
        java_installed: "{{ package_facts.packages | selectattr('name', 'in', java_packages) | map(attribute='name') | list | default([]) }}"

    - name: Write Java package facts to CSV file
      lineinfile:
        path: "/var/tmp/java_packages_{{ ansible_date_time.date }}.csv"
        line: "{{ ansible_facts['hostname'] }},{{ java_installed | join(',') }}"
        create: true
      when: redhat and java_installed
