- name: Gather Java package facts
  hosts: all
  gather_facts: true
  vars:
    java_packages:
      - java
      - jdk
      - jre
    output_host: "{{ groups['collection'][0] }}"
  tasks:
    - name: Get installed Java packages
      command: rpm -qa | grep "{{ java_packages | join(' ') }}"
      register: java_packages_output
      ignore_errors: yes

    - name: Detect RPM database corruption
      command: rpm --rebuilddb --quiet
      ignore_errors: yes
      register: rpm_rebuild_output
      changed_when: rpm_rebuild_output.rc == 0 and java_packages_output.rc != 0

    - name: Get installed Java packages (retry after RPM repair)
      command: rpm -qa | grep "{{ java_packages | join(' ') }}"
      register: java_packages_output
      when: rpm_rebuild_output.changed

    - name: Filter for Red Hat 7 and above
      set_fact:
        redhat: "{{ ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] | int >= 7 }}"

    - name: Filter for Java packages
      set_fact:
        java_installed: "{{ java_packages_output.stdout_lines }}"

    - name: Write Java package facts to CSV file
      delegate_to: "{{ output_host }}"
      lineinfile:
        dest: /opt/java_packages.csv
        line: "{{ ansible_facts['hostname'] }},{{ java_installed | join(',') }}"
      when: redhat and java_installed
