- name: Gather Java package facts
  hosts: all
  gather_facts: true
  vars:
    java_packages:
      - java
      - jdk
      - jre
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
      register: package_facts

    - name: Filter for Red Hat 7 and above
      set_fact:
        redhat: "{{ ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] | int >= 7 }}"

    - name: Filter for Java packages
      set_fact:
        java_installed: "{{ package_facts.packages | selectattr('name', 'in', java_packages) | map(attribute='name') | list }}"

    - name: Write Java package facts to CSV file
      lineinfile:
        path: /tmp/java_packages.csv
        line: "{{ ansible_facts['hostname'] }},{{ java_installed | join(',') }}"
      when: redhat and java_installed

    - name: Email Java package facts CSV file
      mail:
        host: smtp.example.com
        port: 25
        to: admin@example.com
        subject: Java package facts
        body: Java package facts are attached.
        attach:
          - /tmp/java_packages.csv
      when: redhat and java_installed
