---
- hosts: all
  become: true
  gather_facts: false

  vars:
    mount_point: "/app"

  tasks:
  - name: Gather detailed block device mappings
    ansible.builtin.shell:
      cmd: "lsblk -o NAME,PKNAME,HCTL,MOUNTPOINT -P | grep 'MOUNTPOINT=\"{{ mount_point }}\"'"
    register: mount_details
    changed_when: false

  - name: Debug mount details (optional)
    ansible.builtin.debug:
      msg: "{{ mount_details.stdout_lines }}"

  - name: Fail if no mount details found
    ansible.builtin.fail:
      msg: "No mount details found for the specified mount point: {{ mount_point }}"
    when: mount_details.stdout == ""

  # Method 2 (fixed):
  - name: Parse PKNAME from mount details (Method 2 - Fixed)
    ansible.builtin.set_fact:
      pkname: "{{ mount_details.stdout | regex_replace('PKNAME=\"([^\"]+)\"', '\\1', True) | default('') }}"

  - name: Debug PKNAME
    ansible.builtin.debug:
      msg: "PKNAME extracted: {{ pkname }}"

  - name: Gather SCSI details of the parent kernel device
    ansible.builtin.shell:
      cmd: "lsblk -o NAME,HCTL -P | grep 'NAME=\"{{ pkname }}\"'"
    register: scsi_details

  - name: Extract SCSI HCTL
    ansible.builtin.set_fact:
      scsi_hctl: "{{ scsi_details.stdout | regex_search('HCTL=\"([^\"]+)\"', '\\1') | default('N/A') }}"

  - name: Display SCSI and physical disk information
    ansible.builtin.debug:
      msg: >
        Mount Point: {{ mount_point }},
        Physical Disk: /dev/{{ pkname }},
        SCSI HCTL: {{ scsi_hctl }}
