---
- name: Trace LVM to Physical Disk and Retrieve SCSI Information
  hosts: all
  become: true
  gather_facts: false

  vars:
    mount_point: "/app"

  tasks:
    - name: Gather block device information including parent devices
      ansible.builtin.shell: |
        lsblk -o NAME,PKNAME,HCTL,SIZE,MOUNTPOINT | grep '{{ mount_point }}' || echo "No match found"
      register: lvm_to_disk_map
      changed_when: false

    - name: Check if LVM mapping was successful
      ansible.builtin.fail:
        msg: "No LVM or physical disk could be identified for the mount point: {{ mount_point }}"
      when: '"No match found" in lvm_to_disk_map.stdout'

    - name: Set physical disk details from the mapping
      set_fact:
        disk_info: "{{ lvm_to_disk_map.stdout_lines | last }}"  # Assuming the relevant line is the last if more than one
        physical_disk_name: "{{ disk_info | regex_findall('^(\\S+)', ignorecase=True) | first }}"
        scsi_hctl: "{{ disk_info | regex_findall('([0-9]+:[0-9]+:[0-9]+:[0-9]+)', ignorecase=True) | first }}"
        disk_size: "{{ disk_info | regex_findall('(\\d+G)', ignorecase=True) | first }}"

    - name: Display final details
      ansible.builtin.debug:
        msg: >
          Mount Point: {{ mount_point }},
          Physical Disk: /dev/{{ physical_disk_name | default('unknown') }},
          SCSI HCTL: {{ scsi_hctl | default('N/A') }},
          Disk Size: {{ disk_size | default('N/A') }}
