---
- name: Display Disk Details for a Mount Point
  hosts: all
  become: true
  gather_facts: false

  vars:
    mount_point: "/app"

  tasks:
    - name: Gather block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MOUNTPOINT
      register: lsblk_output

    - name: Determine block device from mount point
      set_fact:
        block_device_details: "{{ lsblk_output.stdout_lines | select('search', 'MOUNTPOINT=\"' + mount_point + '\"') | list }}"
      no_log: false

    - name: Extract and display details
      ansible.builtin.debug:
        msg: >
          Mount Point: {{ mount_point }},
          LVM Name: /dev/{{ block_device_details | map('regex_findall', 'NAME="([^"]+)"') | first | first }},
          SCSI HCTL: {{ block_device_details | map('regex_findall', 'HCTL="([^"]+)"') | first | first | default('N/A') }},
          Size: {{ block_device_details | map('regex_findall', 'SIZE="([^"]+)"') | first | first | default('N/A') }} GB
      when: block_device_details | length > 0

    - name: Fail if no device found
      ansible.builtin.fail:
        msg: "No device found mounted at {{ mount_point }}"
      when: block_device_details | length == 0
