---
- name: Trace LVM to Physical Disk and Retrieve SCSI Information
  hosts: all
  become: true
  gather_facts: false

  vars:
    mount_point: "/app"  # Update this to the desired mount point

  tasks:
    - name: Gather block device information including parent devices
      ansible.builtin.shell:
        cmd: lsblk -o NAME,PKNAME,HCTL,SIZE,MOUNTPOINT
      register: lsblk_output
      changed_when: false

    - name: Debug lsblk output
      ansible.builtin.debug:
        msg: "{{ lsblk_output.stdout_lines }}"

    - name: Filter for specific mount point
      set_fact:
        filtered_output: "{{ lsblk_output.stdout_lines | select('contains', mount_point) | list }}"
      failed_when: filtered_output | length == 0

    - name: Debug filtered output
      ansible.builtin.debug:
        msg: "{{ filtered_output }}"

    - name: Extract physical disk details from the mapping
      set_fact:
        disk_info: "{{ filtered_output | last }}"
      failed_when: disk_info is undefined

    - name: Extract disk name and SCSI HCTL
      set_fact:
        physical_disk_name: "{{ disk_info | regex_findall('^\\S+', ignorecase=True) | first }}"
        scsi_hctl: "{{ disk_info | regex_findall('[0-9]+:[0-9]+:[0-9]+:[0-9]+', ignorecase=True) | first }}"

    - name: Display final details
      ansible.builtin.debug:
        msg: >
          Mount Point: {{ mount_point }},
          Physical Disk: /dev/{{ physical_disk_name | default('unknown') }},
          SCSI HCTL: {{ scsi_hctl | default('N/A') }},
          Disk Size: {{ disk_info | regex_findall('\\d+\\.\\d+G', ignorecase=True) | first | default('N/A') }}
