---
- name: Find Disk with Specific Mount Point
  hosts: all
  become: yes
  gather_facts: no  # Set to 'no' initially, we'll manually gather hardware facts

  vars:
    mount_point: "/app"  # Define the mount point you're interested in

  tasks:
    - name: Gather hardware facts
      ansible.builtin.setup:
        gather_subset:
          - "mounts"  # Gather only mount-related facts

    - name: Find the disk with the specified mount point
      ansible.builtin.debug:
        msg: >
          The disk mounted on {{ mount_point }} is {{ item.device }}
          with size {{ item.size_total | default('unknown size') }} bytes
      loop: "{{ ansible_mounts }}"
      when: item.mount == mount_point
