---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Filter and display relevant disk information
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - "'FSTYPE=\"xfs\"' in item or 'FSTYPE=\"ext4\"' in item"
        - "'MOUNTPOINT=\"' not in item or regex_search('MOUNTPOINT=\"[^\"].+\"', item)"

    - name: Display formatted disk information
      ansible.builtin.debug:
        msg: >
          Mount Point: {{ item | regex_findall('MOUNTPOINT="([^"]+)"') | first }},
          Device: /dev/{{ item | regex_findall('NAME="([^"]+)"') | first }},
          SCSI Info: {{ item | regex_findall('HCTL="([0-9]+:[0-9]+:[0-9]+:[0-9]+)"') | first | default('N/A') }},
          Filesystem Type: {{ item | regex_findall('FSTYPE="([^"]+)"') | first }}
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - "'FSTYPE=\"xfs\"' in item or 'FSTYPE=\"ext4\"' in item"
        - "'MOUNTPOINT=\"' not in item or regex_search('MOUNTPOINT=\"[^\"].+\"', item)"
