---
- name: Identify Disk and SCSI Information for a Specific Mount Point
  hosts: all
  become: yes
  gather_facts: no

  vars:
    var_mount: "/app"  # The mount point, can be set dynamically at runtime if needed

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MOUNTPOINT
      register: lsblk_output

    - name: Extract disk information for the specified mount point
      ansible.builtin.set_fact:
        disk_details: "{{ item }}"
      loop: "{{ lsblk_output.stdout_lines }}"
      when: "'MOUNTPOINT=\"' + var_mount + '\"' in item and 'TYPE=\"part\"' in item"
      no_log: true

    - name: Display disk information
      ansible.builtin.debug:
        msg: >
          Mount: {{ var_mount }},
          Disk: {{ disk_details | regex_findall('NAME="([^"]+)"') | first }},
          Size: {{ disk_details | regex_findall('SIZE="([^"]+)"') | first }},
          SCSI Info: {{ (disk_details | regex_findall('HCTL="([0-9]+):([0-9]+):([0-9]+):([0-9]+)"') | first | default('N/A')) | regex_replace('^([0-9]+):([0-9]+):([0-9]+):([0-9]+)$', '0:\\3') }}
      when: disk_details is defined
