---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Parse and display block device information
      ansible.builtin.debug:
        msg: >-
          {{
            lsblk_output.stdout_lines
            | map('regex_replace', 'NAME="([^"]+)" HCTL="([^"]*)" TYPE="([^"]*)" SIZE="([^"]*)" MODEL="([^"]*)" MOUNTPOINT="([^"]*)" FSTYPE="([^"]*)"', {'name': '\1', 'hctl': '\2', 'type': '\3', 'size': '\4', 'model': '\5', 'mountpoint': '\6', 'fstype': '\7'})
            | selectattr('fstype', 'in', ['xfs', 'ext4'])
            | selectattr('mountpoint', 'ne', '')
            | map('regex_replace', 'hctl="([0-9]+):([0-9]+):([0-9]+):([0-9]+)"', 'SCSI Info: 0:\3')
            | map('regex_replace', 'mountpoint="([^"]+)"', 'Mount Point: \1')
            | map('regex_replace', 'name="([^"]+)"', 'Device: /dev/\1')
            | list
          }}
