---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Parse and display block device information
      ansible.builtin.debug:
        msg: >
          {{
            lsblk_output.stdout_lines
            | select('search', 'FSTYPE="(xfs|ext4)"')  # Filter lines with xfs or ext4 filesystems
            | select('search', 'MOUNTPOINT!=""')  # Ensure the mount point is not empty
            | map('regex_replace', 'NAME="([^"]+)" HCTL="([^"]*)" TYPE="([^"]*)" SIZE="([^"]*)" MODEL="([^"]*)" MOUNTPOINT="([^"]+)" FSTYPE="([^"]+)"', 'Device: /dev/\\1, Mount Point: \\6, SCSI Info: \\2, FSTYPE: \\7')
            | list
          }}
