---
- name: Dynamically correlate LVs with PVs and retrieve SCSI information
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Filter and display relevant LVs and their SCSI information
      ansible.builtin.debug:
        msg: >
          Logical Volume: /dev/{{ item | regex_findall('NAME="([^"]+)"') | first }},
          Mount Point: {{ item | regex_findall('MOUNTPOINT="([^"]+)"') | first }},
          SCSI Info for underlying disk: {{ (lsblk_output.stdout_lines | select('search', 'TYPE="disk"') | list | json_query("[?contains(NAME, '" + (item | regex_findall('NAME="([^"]+)"') | first) + "')].HCTL")) | first | default('N/A') }},
          Filesystem Type: {{ item | regex_findall('FSTYPE="([^"]+)"') | first | default('N/A') }}
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - "'FSTYPE=\"xfs\"' in item or 'FSTYPE=\"ext4\"' in item"
        - "'MOUNTPOINT!=\"\"' in item"
        - not "'NAME=\"vg00' in item"
        - not "'NAME=\"vg0' in item"
