---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Display each disk information
      ansible.builtin.debug:
        msg: "Mount Point: {{ item.split(' ')[5].split('=')[1].strip('\"') }}, Device: /dev/mapper/{{ item.split(' ')[0].split('=')[1].strip('\"') }}, Volume Group: vg01, SCSI Info: {{ item.split(' ')[1].split('=')[1].strip('\"').split(':')[2] }}"
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - "'FSTYPE=\"xfs\"' in item or 'FSTYPE=\"ext4\"' in item"
        - "'MOUNTPOINT' in item and item.split(' ')[5].split('=')[1] != '\"\"'"
