---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather filesystem mount information
      ansible.builtin.command:
        cmd: df -hT
      register: df_output

    - name: Display filesystem mount information
      ansible.builtin.debug:
        var: df_output.stdout_lines

    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Display detailed block device information
      ansible.builtin.debug:
        var: lsblk_output.stdout_lines

    - name: Gather volume group information
      ansible.builtin.command:
        cmd: vgs --noheadings -o vg_name,pv_name
      register: vgs_output

    - name: Display volume group information
      ansible.builtin.debug:
        var: vgs_output.stdout_lines

    - name: Parse lsblk output
      ansible.builtin.set_fact:
        disks_info: >-
          {{
            lsblk_output.stdout_lines | map('regex_search', '^NAME="(?P<name>.*?)" HCTL="(?P<hctl>.*?)" TYPE="(?P<type>.*?)" SIZE="(?P<size>.*?)" MODEL="(?P<model>.*?)" MOUNTPOINT="(?P<mountpoint>.*?)" FSTYPE="(?P<fstype>.*?)"$')
            | select('defined')
            | list
          }}

    - name: Display parsed lsblk output
      ansible.builtin.debug:
        var: disks_info

    - name: Gather detailed information about mounts
      ansible.builtin.command:
        cmd: lvdisplay
      register: lvdisplay_output

    - name: Parse lvdisplay output
      ansible.builtin.set_fact:
        lv_info: >-
          {{
            lvdisplay_output.stdout | regex_findall('VG Name\\s+(\\S+).*?LV Path\\s+(\\S+)', multiline=True)
            | map('list')
            | map('zip', ['vg_name', 'lv_path'])
            | map('items2dict')
          }}

    - name: Display parsed lvdisplay output
      ansible.builtin.debug:
        var: lv_info

    - name: Filter disks and match with mount points
      ansible.builtin.set_fact:
        filtered_disks: >-
          {{
            disks_info | selectattr('mountpoint', 'defined')
                       | rejectattr('fstype', 'eq', '')
                       | selectattr('fstype', 'in', ['xfs', 'ext4'])
                       | rejectattr('mountpoint', 'in', ['/boot', '/boot/efi'])
                       | map('combine', {
                            'mountpoint': item.mountpoint,
                            'device': lv_info | selectattr('lv_path', 'search', item.mountpoint) | map(attribute='lv_path') | first,
                            'vg_name': lv_info | selectattr('lv_path', 'search', item.mountpoint) | map(attribute='vg_name') | first,
                            'scsi_info': item.hctl | regex_replace('^[0-9]+:([0-9]+):([0-9]+):[0-9]+$', '\\1:\\2')
                          })
                       | selectattr('vg_name', 'defined')
                       | rejectattr('vg_name', 'in', ['vg0', 'vg00'])
                       | list
          }}

    - name: Display filtered disks
      ansible.builtin.debug:
        var: filtered_disks
