---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Initialize an empty list for storing parsed data
      ansible.builtin.set_fact:
        parsed_data: []

    - name: Parse block device information
      ansible.builtin.set_fact:
        parsed_data: "{{ parsed_data + [item] }}"
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - "'FSTYPE=\"xfs\"' in item or 'FSTYPE=\"ext4\"' in item"
        - "'MOUNTPOINT=\"' not in item or item | regex_search('MOUNTPOINT=\"[^"]+\"')"

    - name: Display each disk information
      ansible.builtin.debug:
        msg: >
          Mount Point: {{ item | regex_search('MOUNTPOINT=\"([^"]+)\"', '\\1') | first }},
          Device: /dev/{{ item | regex_search('NAME=\"([^"]+)\"', '\\1') | first }},
          SCSI Info: {{ item | regex_search('HCTL=\"([0-9]+:[0-9]+:[0-9]+:[0-9]+)\"', '\\1') | first | default('N/A') }}
      loop: "{{ parsed_data }}"
