---
- name: Identify filesystems and their corresponding SCSI devices based on user-defined mount point
  hosts: all
  become: yes
  gather_facts: yes
  vars_prompt:
    - name: user_mount
      prompt: "Enter the mount point you want to check (e.g., /app)"
      private: no

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Display disk information for specified mount point
      ansible.builtin.debug:
        msg: >
          Logical Volume: /dev/{{ item | regex_findall('NAME="([^"]+)"') | first | default('N/A') }},
          Mount Point: {{ user_mount }},
          SCSI Info: {{ item | regex_findall('HCTL="([0-9]+:[0-9]+:[0-9]+:[0-9]+)"') | first | default('N/A') }},
          Filesystem Type: {{ item | regex_findall('FSTYPE="([^"]+)"') | first | default('N/A') }}
      loop: "{{ lsblk_output.stdout_lines }}"
      when: 
        - item | regex_search('MOUNTPOINT="' + user_mount + '"')
