---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Parse and display lsblk output
      ansible.builtin.debug:
        msg: >
          {{
            lsblk_output.stdout_lines
            | map('regex_replace', 'NAME="(?P<name>.+?)" HCTL="(?P<hctl>.+?)" TYPE="(?P<type>.+?)" SIZE="(?P<size>.+?)" MODEL="(?P<model>.+?)" MOUNTPOINT="(?P<mountpoint>.+?)" FSTYPE="(?P<fstype>.+?)"', '\\g<name>,\\g<hctl>,\\g<type>,\\g<size>,\\g<model>,\\g<mountpoint>,\\g<fstype>')
            | list
          }}

    - name: Filter and display relevant disk information
      ansible.builtin.debug:
        msg: >
          {{
            lsblk_output.stdout_lines
            | map('regex_replace', 'NAME="(?P<name>.+?)" HCTL="(?P<hctl>.+?)" TYPE="(?P<type>.+?)" SIZE="(?P<size>.+?)" MODEL="(?P<model>.+?)" MOUNTPOINT="(?P<mountpoint>.+?)" FSTYPE="(?P<fstype>.+?)"', '\\g<name>,\\g<hctl>,\\g<type>,\\g<size>,\\g<model>,\\g<mountpoint>,\\g<fstype>')
            | select('match', '.*,.*,.*,.*,.*,.*ext4|xfs,.*')
            | map('regex_replace', '.*,0:0:(?P<id>\d+):0,.*,.*,/(?P<mount>.*),ext4|xfs', 'Mount Point: /\\g<mount>\nDevice: /dev/mapper/vg01-\\g<mount>\nVolume Group: vg01\nSCSI Info: 0:\\g<id>')
            | list
          }}
