---
- name: Identify filesystems and their corresponding SCSI devices in RedHat Guest OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather detailed block device information
      ansible.builtin.command:
        cmd: lsblk -P -o NAME,HCTL,TYPE,SIZE,MODEL,MOUNTPOINT,FSTYPE
      register: lsblk_output

    - name: Parse and filter block device information
      ansible.builtin.set_fact:
        parsed_disks_info: >-
          {{
            lsblk_output.stdout_lines
            | select('match', '^NAME=.*MOUNTPOINT=.*FSTYPE="(xfs|ext4)"')
            | map('regex_replace', '^(?:[^"]*"([^"]*)"){6}([^"]*)$', '\\2')  # Extract the MOUNTPOINT
            | list
          }}

    - name: Extract detailed information about each disk
      ansible.builtin.set_fact:
        detailed_disks_info: >-
          {{
            lsblk_output.stdout_lines
            | select('match', '^NAME=.*MOUNTPOINT=.*FSTYPE="(xfs|ext4)"')
            | map('regex_replace', '^(?:[^"]*"([^"]*)"){2}([^"]*)$', '\\2')  # Extract the HCTL
            | map('regex_replace', '^[0-9]:[0-9]:([0-9]+):[0-9]$', '0:\\1')  # Format as "0:TargetID"
            | list
          }}

    - name: Display parsed block device information
      ansible.builtin.debug:
        msg: "{{ item.0 }} is mounted at {{ item.1 }}, SCSI Info: {{ item.2 }}"
      with_together:
        - "{{ detailed_disks_info }}"
        - "{{ parsed_disks_info }}"
